/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BreederDashboardRouteImport } from './routes/breeder-dashboard'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HowEscrowWorksRouteImport } from './routes/how-escrow-works'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as PigeonBossAdminRouteImport } from './routes/pigeon-boss-admin'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as RefCodeRouteImport } from './routes/ref.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BreederDashboardRoute = BreederDashboardRouteImport.update({
  id: '/breeder-dashboard',
  path: '/breeder-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HowEscrowWorksRoute = HowEscrowWorksRouteImport.update({
  id: '/how-escrow-works',
  path: '/how-escrow-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PigeonBossAdminRoute = PigeonBossAdminRouteImport.update({
  id: '/pigeon-boss-admin',
  path: '/pigeon-boss-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breeder-dashboard': typeof BreederDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/how-escrow-works': typeof HowEscrowWorksRoute
  '/messages': typeof MessagesRoute
  '/my-orders': typeof MyOrdersRoute
  '/pigeon-boss-admin': typeof PigeonBossAdminRoute
  '/listing/$id': typeof ListingIdRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breeder-dashboard': typeof BreederDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/how-escrow-works': typeof HowEscrowWorksRoute
  '/messages': typeof MessagesRoute
  '/my-orders': typeof MyOrdersRoute
  '/pigeon-boss-admin': typeof PigeonBossAdminRoute
  '/listing/$id': typeof ListingIdRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breeder-dashboard': typeof BreederDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/how-escrow-works': typeof HowEscrowWorksRoute
  '/messages': typeof MessagesRoute
  '/my-orders': typeof MyOrdersRoute
  '/pigeon-boss-admin': typeof PigeonBossAdminRoute
  '/listing/$id': typeof ListingIdRoute
  '/ref/$code': typeof RefCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breeder-dashboard'
    | '/feedback'
    | '/how-escrow-works'
    | '/messages'
    | '/my-orders'
    | '/pigeon-boss-admin'
    | '/listing/$id'
    | '/ref/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breeder-dashboard'
    | '/feedback'
    | '/how-escrow-works'
    | '/messages'
    | '/my-orders'
    | '/pigeon-boss-admin'
    | '/listing/$id'
    | '/ref/$code'
  id:
    | '__root__'
    | '/'
    | '/breeder-dashboard'
    | '/feedback'
    | '/how-escrow-works'
    | '/messages'
    | '/my-orders'
    | '/pigeon-boss-admin'
    | '/listing/$id'
    | '/ref/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreederDashboardRoute: typeof BreederDashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  HowEscrowWorksRoute: typeof HowEscrowWorksRoute
  MessagesRoute: typeof MessagesRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PigeonBossAdminRoute: typeof PigeonBossAdminRoute
  ListingIdRoute: typeof ListingIdRoute
  RefCodeRoute: typeof RefCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeder-dashboard': {
      id: '/breeder-dashboard'
      path: '/breeder-dashboard'
      fullPath: '/breeder-dashboard'
      preLoaderRoute: typeof BreederDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-escrow-works': {
      id: '/how-escrow-works'
      path: '/how-escrow-works'
      fullPath: '/how-escrow-works'
      preLoaderRoute: typeof HowEscrowWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pigeon-boss-admin': {
      id: '/pigeon-boss-admin'
      path: '/pigeon-boss-admin'
      fullPath: '/pigeon-boss-admin'
      preLoaderRoute: typeof PigeonBossAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreederDashboardRoute: BreederDashboardRoute,
  FeedbackRoute: FeedbackRoute,
  HowEscrowWorksRoute: HowEscrowWorksRoute,
  MessagesRoute: MessagesRoute,
  MyOrdersRoute: MyOrdersRoute,
  PigeonBossAdminRoute: PigeonBossAdminRoute,
  ListingIdRoute: ListingIdRoute,
  RefCodeRoute: RefCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
